name: "Action 1: Download Example Template"

on:
  workflow_dispatch:

jobs:
  download-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 3000 &
          echo $! > server.pid
          sleep 10

      - name: Download example template
        run: |
          curl -OJ http://localhost:3000/api/v1/download/example-combination-data
          ls -lh example-combination-data.xlsx

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
          fi

      - name: Upload example template
        uses: actions/upload-artifact@v4
        with:
          name: example-template
          path: example-combination-data.xlsx
          retention-days: 7
